name: Update Theme Version Info

on:
  push:
    tags:
      - 'v*'

jobs:
  update-theme-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important to get all history

      - name: Set version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create GitHub Release (if not exists)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: "Automated release for theme version ${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get last commit message
        id: get_commit_message
        run: |
          # Get the commit message of the last commit for the tagged commit
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B ${{ github.ref }})
          # Escape double quotes for JSON
          ESCAPED_COMMIT_MESSAGE=$(echo "$LAST_COMMIT_MESSAGE" | sed 's/"/\\"/g')
          echo "COMMIT_MESSAGE=$ESCAPED_COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Update style.css version
        run: |
          sed -i "s/^Version: .*/Version: $VERSION/" style.css

      - name: Update theme-update-info.json
        run: |
          cat > theme-update-info.json <<EOF
          {
            "version": "${VERSION}",
            "details_url": "https://github.com/${{ github.repository }}/releases/tag/${VERSION}",
            "download_url": "https://github.com/${{ github.repository }}/archive/refs/tags/${VERSION}.zip",
            "requires": "5.0",
            "tested": "6.5",
            "last_updated": "$(date +'%Y-%m-%d')",
            "sections": {
              "changelog": "${{ env.COMMIT_MESSAGE }}"
            }
          }
          EOF

      - name: Commit and push updated files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add style.css theme-update-info.json
          git commit -m "Update theme version info for ${VERSION}" || echo "No changes to commit"
          git push origin HEAD:refs/heads/main  # Push to main branch