name: Update Theme Version Info

on:
  push:
    tags:
      - 'v*'

jobs:
  update-theme-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create GitHub Release (if not exists)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: "Automated release for theme version ${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release info
        id: get_release
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/releases/tags/${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update style.css version
        run: |
          sed -i "s/^Version: .*/Version: $VERSION/" wp-content/themes/dsnshowcase/style.css

      - name: Update theme-update-info.json
        run: |
          cat > wp-content/themes/dsnshowcase/theme-update-info.json <<EOF
          {
            "version": "${VERSION}",
            "details_url": "https://github.com/${{ github.repository }}/releases/tag/${VERSION}",
            "download_url": "https://github.com/${{ github.repository }}/archive/refs/tags/${VERSION}.zip",
            "requires": "5.0",
            "tested": "6.5",
            "last_updated": "$(date +'%Y-%m-%d')",
            "sections": {
              "changelog": ${{
                steps.get_release.outputs.data && fromJson(steps.get_release.outputs.data).body 
              }}
            }
          }
          EOF

      - name: Commit and push updated files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add wp-content/themes/dsnshowcase/style.css wp-content/themes/dsnshowcase/theme-update-info.json
          git commit -m "Update theme version info for ${VERSION}"
          git push origin main